### ISSUE TITLE
Share via browser does not show any link when using the hotspot

### ISSUE THREAD

**Issue by Hocuri** [genonbeta/TrebleShot#106]
**Describe the bug**
When using the hotspot, the "share via browser" activity does not show the link. (ip address plus port)

**To Reproduce**
1. Tap "Receive" 
2. "Set up hotspot"
3. "Start hotspot"
4. Back to main activity
5. "Share via browser"
6. Back to main activity
7. "Share via browser"
8. push the green start button

Note that I could reproduce this on this particular phone but not on another one.

**Expected behavior**
A link like "http://192.169..." should be shown

**Actual behavior**
it only says "Networks you connect appear here"

**Log files**
(adb, hope that's ok)
```
2019-10-20 12:21:14.953 891-6849/system_process I/ActivityManager: START u0 {cmp=com.genonbeta.TrebleShot/.activity.ConnectionManagerActivity (has extras)} from uid 10346 on display 0
2019-10-20 12:21:14.988 16038-16038/com.genonbeta.TrebleShot:transfer D/CommunicationService: onStart() : action = com.genonbeta.TrebleShot.transaction.action.SERVICE_STATUS
2019-10-20 12:21:15.067 16038-16038/com.genonbeta.TrebleShot:transfer D/CommunicationService: onStart() : action = com.genonbeta.TrebleShot.transaction.action.SERVICE_STATUS
2019-10-20 12:21:15.194 16019-16077/com.genonbeta.TrebleShot V/NsdDiscovery: NSD discovery started
2019-10-20 12:21:15.194 16019-16077/com.genonbeta.TrebleShot V/NsdDiscovery: NSD service is now found which is of TSComm_1571566854
2019-10-20 12:21:15.195 16019-16077/com.genonbeta.TrebleShot V/NsdDiscovery: NSD service is now found which is of TSComm_1571566854
2019-10-20 12:21:15.200 16019-16077/com.genonbeta.TrebleShot E/NsdDiscovery: Resolve failed for TSComm_1571566854
2019-10-20 12:21:15.209 16019-16077/com.genonbeta.TrebleShot V/NsdDiscovery: Resolved with success TSComm_1571566854 with IP address of 127.0.0.1
2019-10-20 12:21:15.243 16038-16079/com.genonbeta.TrebleShot:transfer I/System.out: CoolSocket: You should close connections in the end of onConnected(ActiveConnection) method
2019-10-20 12:21:15.312 891-1397/system_process I/ActivityManager: Displayed com.genonbeta.TrebleShot/.activity.ConnectionManagerActivity: +321ms
2019-10-20 12:21:15.344 16019-16019/com.genonbeta.TrebleShot E/RecyclerView: No adapter attached; skipping layout
2019-10-20 12:21:16.383 16019-16077/com.genonbeta.TrebleShot V/NsdDiscovery: NSD discovery stopped
2019-10-20 12:21:16.520 16019-16028/com.genonbeta.TrebleShot I/System.out: CoolSocket: Connections should be closed before their references are being destroyed
2019-10-20 12:21:17.404 16038-16038/com.genonbeta.TrebleShot:transfer D/CommunicationService: onStart() : action = com.genonbeta.TrebleShot.transaction.action.TOGGLE_HOTSPOT
2019-10-20 12:21:17.421 16038-16038/com.genonbeta.TrebleShot:transfer D/CommunicationService: setupHotspot(): Start with TrustZone
2019-10-20 12:21:18.143 16019-16019/com.genonbeta.TrebleShot D/PreferenceUtils: Put setting: dark_theme => false
2019-10-20 12:21:18.143 16019-16019/com.genonbeta.TrebleShot D/PreferenceUtils: Put setting: device_name => Jonathan
2019-10-20 12:21:18.143 16019-16019/com.genonbeta.TrebleShot D/PreferenceUtils: Put setting: introduction_shown => true
2019-10-20 12:21:18.143 16019-16019/com.genonbeta.TrebleShot D/PreferenceUtils: Put setting: notification_light => true
2019-10-20 12:21:18.143 16019-16019/com.genonbeta.TrebleShot D/PreferenceUtils: Put setting: notification_sound => true
2019-10-20 12:21:18.143 16019-16019/com.genonbeta.TrebleShot D/PreferenceUtils: Put setting: __SYNC_TIME => 1571566878050
2019-10-20 12:21:18.143 16019-16019/com.genonbeta.TrebleShot D/PreferenceUtils: Put setting: allow_autoconnect => false
2019-10-20 12:21:18.143 16019-16019/com.genonbeta.TrebleShot D/PreferenceUtils: Put setting: nsd_enabled => true
2019-10-20 12:21:18.143 16019-16019/com.genonbeta.TrebleShot D/PreferenceUtils: Put setting: hotspot_trust => true
2019-10-20 12:21:18.143 16019-16019/com.genonbeta.TrebleShot D/PreferenceUtils: Put setting: pin => 1571566879
2019-10-20 12:21:18.143 16019-16019/com.genonbeta.TrebleShot D/PreferenceUtils: Put setting: developer_mode => false
2019-10-20 12:21:18.143 16019-16019/com.genonbeta.TrebleShot D/PreferenceUtils: Put setting: qr_trust => true
2019-10-20 12:21:18.143 16019-16019/com.genonbeta.TrebleShot D/PreferenceUtils: Put setting: scan_devices_auto => false
2019-10-20 12:21:18.143 16019-16019/com.genonbeta.TrebleShot D/PreferenceUtils: Put setting: load_thumbnails => true
2019-10-20 12:21:18.143 16019-16019/com.genonbeta.TrebleShot D/PreferenceUtils: Put setting: amoled_theme => false
2019-10-20 12:21:18.143 16019-16019/com.genonbeta.TrebleShot D/PreferenceUtils: Put setting: show_system_apps => false
2019-10-20 12:21:18.143 16019-16019/com.genonbeta.TrebleShot D/PreferenceUtils: Put setting: notification_vibrate => true
2019-10-20 12:21:18.143 16019-16019/com.genonbeta.TrebleShot D/PreferenceUtils: Put setting: custom_fonts => false
2019-10-20 12:21:18.143 16019-16019/com.genonbeta.TrebleShot D/PreferenceUtils: Put setting: migrated_version => 98
2019-10-20 12:21:18.143 16019-16019/com.genonbeta.TrebleShot D/PreferenceUtils: Put setting: kill_service_on_exit => true
2019-10-20 12:21:18.143 16019-16019/com.genonbeta.TrebleShot D/PreferenceUtils: Put setting: trust_always => false
2019-10-20 12:21:18.143 16019-16019/com.genonbeta.TrebleShot D/PreferenceUtils: Put setting: referral_version => 98
2019-10-20 12:21:18.268 16019-16019/com.genonbeta.TrebleShot D/NetworkSecurityConfig: No Network Security Config specified, using platform default
2019-10-20 12:21:19.110 16019-16077/com.genonbeta.TrebleShot V/NsdDiscovery: NSD discovery started
2019-10-20 12:21:19.110 16019-16077/com.genonbeta.TrebleShot V/NsdDiscovery: NSD service is now found which is of TSComm_1571566854
2019-10-20 12:21:19.110 16019-16077/com.genonbeta.TrebleShot V/NsdDiscovery: NSD service is now found which is of TSComm_1571566854
2019-10-20 12:21:19.115 16019-16077/com.genonbeta.TrebleShot E/NsdDiscovery: Resolve failed for TSComm_1571566854
2019-10-20 12:21:19.123 16019-16077/com.genonbeta.TrebleShot V/NsdDiscovery: Resolved with success TSComm_1571566854 with IP address of 127.0.0.1
2019-10-20 12:21:19.141 16038-16099/com.genonbeta.TrebleShot:transfer I/System.out: CoolSocket: You should close connections in the end of onConnected(ActiveConnection) method
2019-10-20 12:21:19.197 16019-16019/com.genonbeta.TrebleShot E/RecyclerView: No adapter attached; skipping layout
2019-10-20 12:21:19.625 16038-16038/com.genonbeta.TrebleShot:transfer D/CommunicationService: onStart() : action = com.genonbeta.TrebleShot.transaction.action.SERVICE_STATUS
2019-10-20 12:21:19.628 16019-16077/com.genonbeta.TrebleShot V/NsdDiscovery: NSD discovery stopped
2019-10-20 12:21:19.641 16019-16019/com.genonbeta.TrebleShot W/System.err: java.io.FileNotFoundException: /data/user/0/com.genonbeta.TrebleShot/files/profilePicture (No such file or directory)
2019-10-20 12:21:19.642 16019-16019/com.genonbeta.TrebleShot W/System.err:     at java.io.FileInputStream.open(Native Method)
2019-10-20 12:21:19.642 16019-16019/com.genonbeta.TrebleShot W/System.err:     at java.io.FileInputStream.<init>(FileInputStream.java:146)
2019-10-20 12:21:19.642 16019-16019/com.genonbeta.TrebleShot W/System.err:     at android.app.ContextImpl.openFileInput(ContextImpl.java:476)
2019-10-20 12:21:19.642 16019-16019/com.genonbeta.TrebleShot W/System.err:     at android.content.ContextWrapper.openFileInput(ContextWrapper.java:186)
2019-10-20 12:21:19.642 16019-16019/com.genonbeta.TrebleShot W/System.err:     at com.genonbeta.TrebleShot.app.Activity.loadProfilePictureInto(Activity.java:384)
2019-10-20 12:21:19.642 16019-16019/com.genonbeta.TrebleShot W/System.err:     at com.genonbeta.TrebleShot.activity.HomeActivity.createHeaderView(HomeActivity.java:295)
2019-10-20 12:21:19.642 16019-16019/com.genonbeta.TrebleShot W/System.err:     at com.genonbeta.TrebleShot.activity.HomeActivity.onStart(HomeActivity.java:159)
2019-10-20 12:21:19.642 16019-16019/com.genonbeta.TrebleShot W/System.err:     at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1249)
2019-10-20 12:21:19.642 16019-16019/com.genonbeta.TrebleShot W/System.err:     at android.app.Activity.performStart(Activity.java:6701)
2019-10-20 12:21:19.642 16019-16019/com.genonbeta.TrebleShot W/System.err:     at android.app.Activity.performRestart(Activity.java:6775)
2019-10-20 12:21:19.643 16019-16019/com.genonbeta.TrebleShot W/System.err:     at android.app.Activity.performResume(Activity.java:6780)
2019-10-20 12:21:19.643 16019-16019/com.genonbeta.TrebleShot W/System.err:     at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3431)
2019-10-20 12:21:19.643 16019-16019/com.genonbeta.TrebleShot W/System.err:     at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3494)
2019-10-20 12:21:19.643 16019-16019/com.genonbeta.TrebleShot W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1546)
2019-10-20 12:21:19.643 16019-16019/com.genonbeta.TrebleShot W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
2019-10-20 12:21:19.643 16019-16019/com.genonbeta.TrebleShot W/System.err:     at android.os.Looper.loop(Looper.java:154)
2019-10-20 12:21:19.643 16019-16019/com.genonbeta.TrebleShot W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:6186)
2019-10-20 12:21:19.643 16019-16019/com.genonbeta.TrebleShot W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2019-10-20 12:21:19.643 16019-16019/com.genonbeta.TrebleShot W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
2019-10-20 12:21:19.643 16019-16019/com.genonbeta.TrebleShot W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
2019-10-20 12:21:19.647 16038-16038/com.genonbeta.TrebleShot:transfer D/CommunicationService: onStart() : action = com.genonbeta.TrebleShot.transaction.action.SERVICE_STATUS
2019-10-20 12:21:19.658 16038-16038/com.genonbeta.TrebleShot:transfer D/CommunicationService: onStart() : action = com.genonbeta.TrebleShot.transaction.action.REQUEST_TRUSTZONE_STATUS
2019-10-20 12:21:19.660 16019-16019/com.genonbeta.TrebleShot W/ModernAsyncTask: type=1400 audit(0.0:292): avc: denied { read } for uid=10346 name="/" dev="rootfs" ino=1 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0
2019-10-20 12:21:19.663 16038-16038/com.genonbeta.TrebleShot:transfer D/CommunicationService: onStart() : action = com.genonbeta.TrebleShot.transaction.action.REQUEST_TASK_RUNNING_LIST_CHANGE
2019-10-20 12:21:19.673 16019-16019/com.genonbeta.TrebleShot W/ModernAsyncTask: type=1400 audit(0.0:293): avc: denied { read } for uid=10346 name="/" dev="rootfs" ino=1 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0
2019-10-20 12:21:19.751 16019-16019/com.genonbeta.TrebleShot E/RecyclerView: No adapter attached; skipping layout
2019-10-20 12:21:19.762 16019-16019/com.genonbeta.TrebleShot E/RecyclerView: No adapter attached; skipping layout
2019-10-20 12:21:19.785 16019-16019/com.genonbeta.TrebleShot E/RecyclerView: No adapter attached; skipping layout
2019-10-20 12:21:21.743 891-6845/system_process I/ActivityManager: START u0 {cmp=com.genonbeta.TrebleShot/.activity.WebShareActivity} from uid 10346 on display 0
2019-10-20 12:21:21.777 16038-16038/com.genonbeta.TrebleShot:transfer D/CommunicationService: onStart() : action = com.genonbeta.TrebleShot.transaction.action.SERVICE_STATUS
2019-10-20 12:21:21.862 16038-16038/com.genonbeta.TrebleShot:transfer D/CommunicationService: onStart() : action = com.genonbeta.TrebleShot.transaction.action.SERVICE_STATUS
2019-10-20 12:21:21.864 16038-16038/com.genonbeta.TrebleShot:transfer D/CommunicationService: onStart() : action = com.genonbeta.TrebleShot.transaction.action.REQUEST_WEBSHARE_STATUS
2019-10-20 12:21:21.956 891-1397/system_process I/ActivityManager: Displayed com.genonbeta.TrebleShot/.activity.WebShareActivity: +176ms
2019-10-20 12:21:21.974 16019-16019/com.genonbeta.TrebleShot E/RecyclerView: No adapter attached; skipping layout
2019-10-20 12:21:29.296 16038-16038/com.genonbeta.TrebleShot:transfer D/CommunicationService: onStart() : action = com.genonbeta.TrebleShot.transaction.action.TOGGLE_WEBSHARE
```

**Environment (please complete the following information):**
 - Android version: Android N LineageOS
 - Language: English
 - App version 1.4.2
 - Device Model and Brand Motorola Moto G3

**Comment by velitasali** [comment]
Connections are gathered through a very generic mechanism. Unless the interface name defined by the manufacturer starts with `rmnet` which is used by modem, there should not be an issue.
 
So, at this point, a video showing the issue happening would be useful.

**Comment by Hocuri** [comment]
[ScreenRecord-2019-10-20-16-16-44(1).mp4.zip](https://github.com/genonbeta/TrebleShot/files/3747940/ScreenRecord-2019-10-20-16-16-44.1.mp4.zip)
It was not possible to upload an mp4 file.

**Comment by velitasali** [comment]
How about Wi-Fi connection, does it appear?
