### ISSUE TITLE
java.net.SocketException: Software caused connection abort

### ISSUE THREAD

**Issue by g19980115** [genonbeta/TrebleShot#78]
**Describe the bug**
Unable to establish connection.

**To Reproduce**
1. Go to 'profile editor',**Set an avatar image**.
2. send file,Set up hotspot(Oreo device)
3. Stop hotspot(Oreo device)
4. **Set up hotspot again(Oreo device)**
5. Scan QR Code(Other Device)

Hotspots will automatically terminate.

**Expected behavior**
Successful connection.

**Log files**
[trebleshot_log.txt](https://github.com/genonbeta/TrebleShot/files/2896578/trebleshot_log.txt)

logcat:(Oreo device,`transfer` process)
```Java
java.net.SocketException: Software caused connection abort
    at java.net.SocketOutputStream.socketWrite0(Native Method)
    at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:109)
    at java.net.SocketOutputStream.write(SocketOutputStream.java:153)
    at java.io.DataOutputStream.write(DataOutputStream.java:107)
    at java.io.FilterOutputStream.write(FilterOutputStream.java:97)
    at com.genonbeta.CoolSocket.CoolSocket$ActiveConnection.reply(CoolSocket.java:692)
    at com.genonbeta.TrebleShot.service.CommunicationService$CommunicationServer.pushReply(CommunicationService.java:925)
    at com.genonbeta.TrebleShot.service.CommunicationService$CommunicationServer.onConnected(CommunicationService.java:912)
    at com.genonbeta.CoolSocket.CoolSocket$2.run(CoolSocket.java:269)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:457)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
    at java.lang.Thread.run(Thread.java:764)
```
**Screenshots**
![tim 20190223152801](https://user-images.githubusercontent.com/25760230/53283323-b0514080-377f-11e9-830b-347bd2288cb3.png)

**Environment (please complete the following information):**
 - Android version: [Android 8.1.0]
 - Language: [zh-rCN]
 - App version [1.2.8.3-debug]
 - Device Model and Brand [MEIZU 16th]

**Comment by velitasali** [comment]
Hi @g19980115,

Is it always happening? Or does it happen occasionally? 

I am asking this because this was happening to rarely to me, which does not happen nowadays. 

Thanks.

**Comment by g19980115** [comment]
always.

**Comment by g19980115** [comment]
If I don’t take the second and third steps, it will succeed.

**Comment by velitasali** [comment]
Hi @g19980115,

I was able to reproduce the error and I tested it on a Pie device. 

I will investigate it. Thanks.
